language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: pESJg+F1xycH20oUgP1iAQsZNietKYf1FpAg8r7APREUwgH4Qs2V8w9p3jCQ2UNo0aXCsxWmHxcANJwPohLZZ3A1jq5f1mBuVp2vpt977mfAdWpPvMJDKJrD9TjfsfCql9HY7AqMf0IQHITiBicnGeTGst1NdQMPUyEC8EKmhLt6X3lgNKMPXj8YnStSml6RZ6zJ30KthPXxw7sDf6lY72oOMhnfIaMSga35PCgYBgVykG+u2JjlHa2hvc/ukzvD7B3BCwx67w2+UOBedh6MeXOfjytDr5y9Ze51RVqkOgRc1c3WIOe0f7ggwnt0E1L6QrS65Se43HDGWReZX41S3AIwL4WhZfnQsFdZXD1k4ZrOmRKoxlfwKbuS2QY5w2QvFKB5fc8CJSp2i4VwkFyUm5wuPsDlSc9z8hCPI79uLRyFgzHJUx8/UpNPGKtpvxS9q+HS1JQptBTVv/FaNS4JW+5ZXvhqD5VZsRvkfMmw0+9hEFfS3QMoxifq9rJeqqSXTHCzBqdIDHaI/5dtZFoq5+aIGV5gieB9rCa1WaRMZzA3zvCfuuWrTKOM+1ui/fL7wgj3f04e/1/JNJp1wHJhzhxpgM/UDSx78KV3/AyCVwr7y0BvHV4+Hcl1IxyvRp/aRkLccm2lYJg9tDuBZNuUEOXZd5GB21nwetIfB53LUmI=
  app: apricot-sundae-19850
  on:
    repo: fulgonim/landlordscore
